version: '3'

services:
  db:
    image: mysql:8
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

  wp:
    depends_on:
      - db
    build: .
    volumes:
      - ./wp/:/var/www/html
      - ./custom-theme/:/var/www/html/wp-content/themes/custom-theme
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    networks:
      - app-network

  nginx:
    depends_on:
      - db
      - wp
    image: nginx:latest
    volumes:
      - ./wp/:/var/www/html
      - ./custom-theme/:/var/www/html/wp-content/themes/custom-theme
      - ./nginx-conf:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - app-network

volumes:
  dbdata:
  wp:
  custom-theme:

networks:
  app-network:
    driver: bridge
